### ISSUE TITLE
Way to not skip time at end of combat

### ISSUE THREAD

**Issue by mhilbrunner** [Savantford/foundry-weirdwizard#185]
In some edge cases (for example, multiple subsequent combats in Foundry which are part of the same battle) it may be desireable to not automatically skip time when ending the Foundry battle.

We could either make the end combat confirmation dialog have three buttons, instead of OK/Cancel having Skip Time/Don't skip time/Cancel, or we could add a checkbox for this.

The default should remain to skip 1 minute of time after each combat.

**Comment by Savantford** [comment]
Implemented in 2.6.0: https://github.com/Savantford/foundry-weirdwizard/releases/tag/3.6.0
