### ISSUE TITLE
Creating an Expert or Master Path from the character sheet creates a Novice Path.

### ISSUE THREAD

**Issue by JasonSunday** [Savantford/foundry-weirdwizard#208]
When creating a Expert or Master Path from the character sheet's + symbol uses the Novice Path template.
![create-expert-path](https://github.com/Savantford/foundry-weirdwizard/assets/10623958/fc6b81f6-48ec-43d3-bb20-197daaac42bd)
![expert-popup](https://github.com/Savantford/foundry-weirdwizard/assets/10623958/77e8a3e2-f1aa-4a0f-a60f-eb41a2b6dbc8)

**Comment by Savantford** [comment]
Thanks for the report! I'll investigate.

**Comment by Savantford** [comment]
Fixed in 3.6.0: https://github.com/Savantford/foundry-weirdwizard/releases/tag/3.6.0
