### ISSUE TITLE
Add tooltips for common traits, such as weapon properties

### ISSUE THREAD

**Issue by SolarizedRed** [Savantford/foundry-weirdwizard#36]
Request from Wukong on the Discord:
> Can we get tool tips ? Like when we hover over a weapon property it tells us what it does ?

According to Phenomen:
> V11 has built-in tooltips and you can push this data to the item object [like this](https://github.com/pafvel/dragonbane/blob/c78dfa90547334bb67243a06c6483ab43b03828f/modules/item-sheet.js#L36) and then add it to the title attribute.

**Comment by Savantford** [comment]
Implemented in 0.9.3: https://github.com/Savantford/foundry-weirdwizard/releases/tag/0.9.3
