### ISSUE TITLE
A way to prompt attribute/luck rolls from descriptions (See comments)

### ISSUE THREAD

**Issue by Savantford** [Savantford/foundry-weirdwizard#70]

**Comment by mclemente** [comment]
Use inline rolls like `[[/r 1d20 + @attributes.str.value]]` or add shortcuts on `Actor.getRollData()` so it can be triggered like with `@str`.
Luck Rolls can be called with `[[/r 1d20]]{Luck Rolls}`.
If they have more distinction or require using the custom Roll class, consider looking at the way [Inline Roll Commands module](https://github.com/kaelad02/inline-roll-cmd/tree/main) does it.

**Comment by Savantford** [comment]
That's a good idea, thank you!

**Comment by Savantford** [comment]
Implemented in 2.9.0: https://github.com/Savantford/foundry-weirdwizard/releases/tag/2.9.0
